#!/usr/bin/env python3
"""
mobile_css.py — inject (or refresh) the responsive layer on OpenCausation.org pages.

Why this exists
---------------
Every content page is a Design-Canvas export in which ~250 layout declarations
per page live in inline `style="..."` attributes. Inline styles beat any
stylesheet rule, so a normal mobile stylesheet cannot reach them. Rather than
rewrite 12 pages by hand, this script appends one `<style>` block whose rules
target the exact inline substrings via CSS attribute selectors
(`[style*="grid-template-columns:180px 1fr"]`) and override them with
`!important` inside media queries.

Desktop rendering is untouched: every rule lives inside `@media (max-width:...)`.

Idempotent — re-running replaces the previously injected block.

Usage:  python3 tools/mobile_css.py [--check]
"""

import re
import sys
import pathlib

PUBLIC = pathlib.Path(__file__).resolve().parent.parent / "public"

PAGES = [
    "index", "fundamentals", "methodology", "bradford-hill", "legal-standards",
    "examples", "glossary", "references", "about",
    "carpal-tunnel", "low-back-pain", "rotator-cuff",
]

START = "/* == OC-MOBILE-START (generated by tools/mobile_css.py — do not hand-edit) == */"
END = "/* == OC-MOBILE-END == */"

# Label-gutter and multi-column grids that must stack on small screens.
# Small icon/number columns (16/24/42/52/56px + 1fr) are deliberately EXCLUDED —
# they read correctly on a phone and stacking them would break numbered lists.
_G = "grid-template-columns:"
COLLAPSE_GRIDS = [_G + v for v in [
    "180px 1fr", "220px 1fr", "300px 1fr", "1fr 350px",
    "1.3fr 150px 1.4fr", "1.5fr 150px 1.1fr", "1.3fr 170px 1.3fr",
    "1.15fr 1fr", "1fr 1fr",
    "repeat(2,1fr)", "repeat(3,1fr)", "repeat(5,1fr)",
]]

# Small icon-column grids, tightened (not collapsed) on the narrowest screens.
ICON_GRIDS = [_G + v for v in ["56px 1fr", "52px 1fr", "42px 1fr"]]

# Horizontal container gutters: every one uses 48px as its horizontal value.
GUTTER_PADDINGS = [
    "padding:0 48px", "padding:9px 48px", "padding:12px 48px", "padding:44px 48px",
    "padding:60px 48px", "padding:72px 48px", "padding:76px 48px", "padding:80px 48px",
    "padding:84px 48px", "padding:90px 48px", "padding:94px 48px",
]

# Large vertical section padding -> tightened, grouped by first value.
VERTICAL_TIGHTEN = [
    (["padding:94px 48px", "padding:90px 48px", "padding:84px 48px", "padding:84px 0",
      "padding:80px 48px", "padding:80px 0", "padding:78px 0", "padding:76px 48px",
      "padding:76px 0", "padding:72px 48px", "padding:72px 0", "padding:70px 0"], 52),
    (["padding:64px 0", "padding:60px 48px", "padding:60px 0", "padding:56px 0",
      "padding:52px 0"], 40),
    (["padding:44px 48px", "padding:44px 0", "padding:40px 0"], 32),
]

# Display-type scale-down. (tablet, phone) targets keyed by the authored px size.
TYPE_SCALE = {
    78: (52, 38), 64: (44, 33), 62: (42, 32), 60: (42, 32), 58: (40, 31),
    54: (38, 30), 46: (34, 27), 44: (33, 26), 42: (32, 26), 40: (31, 25),
    38: (30, 25), 36: (29, 24), 34: (28, 23), 31: (26, 22), 30: (25, 22),
    28: (24, 21), 27: (24, 21), 25: (22, 20), 24: (22, 20),
}

# Sections authored open at the bottom must stay open when tightened.
OPEN_BOTTOM = [
    "padding:90px 48px 0", "padding:84px 0 0", "padding:80px 0 0", "padding:78px 0 0",
    "padding:76px 0 0", "padding:72px 0 0", "padding:64px 0 0", "padding:52px 0 0",
    "padding:44px 0 0", "padding:40px 0 0",
]

# Full-height hero/section bands with an explicit bottom value.
HERO_BANDS = [
    "padding:84px 0 76px", "padding:70px 0 80px",
    "padding:60px 0 80px", "padding:56px 0 80px",
]

# Desktop-scale gaps between grid/flex tracks.
WIDE_GAPS = ["gap:64px", "gap:56px", "gap:52px", "gap:48px"]

# Card interiors, so text is not pinched inside boxes on a phone.
CARD_PADDINGS = ["padding:%dpx" % n for n in (30, 32, 34, 36, 38, 40)]

# Sub-legible label sizes get a floor on phones.
TINY_FLOOR = {"9px": "10.5px", "10px": "11px", "10.5px": "11px", "11px": "11.5px"}


def serialized(decl):
    """
    Return the form a browser writes back into the style attribute.

    support.js rewrites element.style while processing <helmet>/style-hover, and
    that reserializes every inline declaration. So the text an attribute selector
    must match at runtime is NOT the authored text. Observed transforms:
        "padding:0 48px"                  -> "padding: 0px 48px"
        "grid-template-columns:repeat(3,1fr)" -> "grid-template-columns: repeat(3, 1fr)"
        "flex-wrap:wrap"                  -> "flex-wrap: wrap"
    i.e. a space after the property colon and after commas, and bare `0` -> `0px`.
    """
    prop, _, value = decl.partition(":")
    value = value.strip()
    value = re.sub(r",\s*", ", ", value)
    # Bare zero tokens gain a unit; 0.5em / 0px / 0.02em are left alone.
    value = re.sub(r"(?<![\w.])0(?![\w.])", "0px", value)
    return "%s: %s" % (prop, value)


def sel(patterns):
    """
    Build a grouped attribute-selector list from inline-style substrings.

    Emits BOTH the authored spelling and the browser-serialized spelling so the
    rule holds whether or not support.js has rewritten the attribute yet.
    """
    seen, out = set(), []
    for p in patterns:
        for form in (p, serialized(p)):
            if form not in seen:
                seen.add(form)
                out.append('[style*="%s"]' % form)
    return ",\n".join(out)


def sel_tag(tag, patterns, suffix=""):
    """Same as sel() but with an element prefix and optional pseudo/child suffix."""
    parts = sel(patterns).split(",\n")
    return ",\n".join(tag + s + suffix for s in parts)


def build_css():
    L = []
    A = L.append

    A(START)

    # ---------- shared safety net (all viewports) ----------
    A("img,svg,video{max-width:100%;height:auto}")
    A("a,p,li,h1,h2,h3,h4,td,th,span,div{overflow-wrap:break-word}")

    # ================= TABLET / LARGE PHONE =================
    A("@media (max-width:860px){")

    # Container gutters 48 -> 24
    A(sel(GUTTER_PADDINGS) + "{padding-left:24px!important;padding-right:24px!important}")

    # Vertical rhythm tightened
    for pats, top in VERTICAL_TIGHTEN:
        A(sel(pats) + "{padding-top:%dpx!important;padding-bottom:%dpx!important}" % (top, top))

    # Sections authored open-ended at the bottom keep that intent.
    A(sel(OPEN_BOTTOM) + "{padding-bottom:0!important}")
    A(sel(["padding:60px 48px 44px"]) + "{padding-top:40px!important;padding-bottom:32px!important}")
    A(sel(HERO_BANDS) + "{padding-top:44px!important;padding-bottom:48px!important}")

    # Wide gaps close up
    A(sel(WIDE_GAPS) + "{gap:28px!important}")

    # Grids stack. (After the gap rule so the tighter stacked gap wins.)
    A(sel(COLLAPSE_GRIDS) + "{grid-template-columns:1fr!important;gap:22px!important}")

    # Any un-hinted flex row may wrap rather than squeeze.
    A(sel(["display:flex"]) + "{flex-wrap:wrap}")

    # Masthead: one scrollable row instead of a multi-row wrap under a sticky header.
    A(sel_tag("nav", ["flex-wrap:wrap"]) +
      "{flex-wrap:nowrap!important;overflow-x:auto;overflow-y:hidden;"
      "gap:0 20px!important;padding:2px 0 12px!important;"
      "-webkit-overflow-scrolling:touch;scrollbar-width:none;"
      "-webkit-mask-image:linear-gradient(to right,#000 90%,transparent);"
      "mask-image:linear-gradient(to right,#000 90%,transparent)}")
    A(sel_tag("nav", ["flex-wrap:wrap"], "::-webkit-scrollbar") + "{display:none}")
    A(sel_tag("nav", ["flex-wrap:wrap"], ">a") +
      "{white-space:nowrap;flex:0 0 auto;padding:4px 0}")
    A(sel(["padding:16px 0 12px"]) + "{padding-top:12px!important;padding-bottom:8px!important}")

    # Display type
    for px, (tab, _phone) in sorted(TYPE_SCALE.items(), reverse=True):
        A(sel(["font-size:%dpx" % px]) + "{font-size:%dpx!important}" % tab)

    A("}")

    # ===================== PHONE =====================
    A("@media (max-width:560px){")

    A(sel(GUTTER_PADDINGS) + "{padding-left:18px!important;padding-right:18px!important}")

    for pats, top in VERTICAL_TIGHTEN:
        t = max(28, top - 12)
        A(sel(pats) + "{padding-top:%dpx!important;padding-bottom:%dpx!important}" % (t, t))
    A(sel(OPEN_BOTTOM) + "{padding-bottom:0!important}")

    A(sel(WIDE_GAPS) + "{gap:22px!important}")
    A(sel(COLLAPSE_GRIDS) + "{grid-template-columns:1fr!important;gap:18px!important}")

    # Icon columns tighten but stay two-up.
    A(sel(ICON_GRIDS) + "{grid-template-columns:34px 1fr!important;gap:12px!important}")

    # Card padding relief so text is not pinched inside boxes.
    A(sel(CARD_PADDINGS) + "{padding-left:18px!important;padding-right:18px!important}")

    A(sel_tag("nav", ["flex-wrap:wrap"]) + "{gap:0 17px!important;font-size:12.5px!important}")

    for px, (_tab, phone) in sorted(TYPE_SCALE.items(), reverse=True):
        A(sel(["font-size:%dpx" % px]) + "{font-size:%dpx!important}" % phone)

    for src_px, dst in TINY_FLOOR.items():
        A(sel(["font-size:%s" % src_px]) + "{font-size:%s!important}" % dst)

    A("}")
    A(END)
    return "\n".join(L)


BLOCK_RE = re.compile(r"\n?" + re.escape(START) + r".*?" + re.escape(END) + r"\n?", re.S)


def apply_to(html, css, name):
    """Return `html` with exactly one freshly generated mobile block. Idempotent."""
    # Drop any previously injected block first.
    html = BLOCK_RE.sub("", html)

    if "</style>" not in html:
        raise SystemExit("%s: no <style> block found in <helmet>" % name)

    # Append inside the FIRST <style> block (the one inside <helmet>).
    idx = html.index("</style>")
    return html[:idx] + "\n" + css + "\n" + html[idx:]


def main():
    check = "--check" in sys.argv
    css = build_css()
    changed = []
    for name in PAGES:
        p = PUBLIC / ("%s.html" % name)
        if not p.exists():
            print("  SKIP (missing): %s" % p.name)
            continue
        old = p.read_text(encoding="utf-8")
        new = apply_to(old, css, p.name)
        if new != old:
            changed.append(p.name)
            if not check:
                p.write_text(new, encoding="utf-8")
            print("  %s: %s" % ("would update" if check else "updated", p.name))
        else:
            print("  unchanged: %s" % p.name)
    print("\n%d/%d pages %s." % (len(changed), len(PAGES),
                                 "need updating" if check else "written"))


if __name__ == "__main__":
    main()
